services:

    Pecserke\YamlFixturesBundle\Transformer\ObjectTransformer:

    pecserke_yaml_fixtures.object_transformer.default:
        alias: Pecserke\YamlFixturesBundle\Transformer\ObjectTransformer
        public: true
